seq = "ACTAGGCCGCGGGGCCGCGTGGCCGCGATGGGCCGCGGGCCGCGAAATTGGGCCGCGCCCTCGGGCCGCGTGGCCGCGGTGTGTGGCCGCGGGCCGCGGGGCCGCGCCGTGGCCGCGCGGCCGCGGAGGGCCGCGGTGGCCGCGGGGCCGCGTGGCCGCGGGCCGCGGGCCGCGGTGGGCGAGGCCGCGCCCGGCCGCGGGCCGCGGGCCGCGCTGGCCGCGTGGCCGCGCGGCCGCGGGCCGCGGGCCGCGGGGCCGCGGGCCGCGTCTAGACGGCCGCGTTGGCCGCGTCCTGGCCGCGGGCCGCGAGCCGGGGCCGCGCTCGGCCGCGGGGCCGCGGGCCGCGTGGCCGCGTAGGCCGCGCTAGGCCGCGTTTCAGCGGCCGCGAGGCCGCGCGGCCGCGCGGGCCGCGAGGCCGCGCGCATGAGGGGCCGCGGGCCGCGGGGGCCGCGGGCCGCGGGCCGCGAAGGCCGCGGCGACCGCGGCCGCGCCACAGGCCGCGTGGCCGCGGCCGGCCGCGGGCCGCGGTTCGGCCGCGATAAGGCCGCGTAGGCCGCGAGTCTTCGACGGCCGCGGGCCGCGAGGCCGCGATTGTCACTCCGGGCCGCGGGCCGCGACGAGGCCGCGACTACGAACGGCCGCGAATGACATCCTGGCCGCGCGTCCTGGGCCGCGGGCCGCGGTGAGTGTTATGGCCGCGGGCCGCGCCGGCAGGCCGCGGGCCGCGTCGTGGCCGCGAGCTGGCCGCGCAGGACGGGCCGCGTAGGCCGCGCGGCGGCCGCGGGCCGCGGGCCGCGAGGCCGCGATTTTATCTCAGGGCCGCGTACACCGCGGGGCCGCGCGGCCGCGGGCCGCGTTAGGCCGCGAATAGGGCCGCGGGCCGCGGGCCGCGCATGAGTAGGGCCGCGTGGCCGCGGGCCGCGAGGCCGCGCTCTGGCCGCGCGGCCGCGGGCCGCGATTCCTGAGGCCGCGCGGCCGCG"
t = "GGCCGCGGG"
list1 = list()

for i in range(len(seq)-len(t)+1):
    list1.append(seq[i:i+len(t)])
print(list1)

print("")

list2 = list()

for i in range(len(list1)):
    if list1[i] == t:
        list2.append(i+1)
print(list2) # []..............

print("")

# solution 1. (python ~ while)
"""with open('rosalind_subs.txt') as f:
    s,t= f.read().split()
f.close()

def posicion(inicio):
      return s.find(t,inicio)

pos=posicion(0)

while pos <> -1:
      print pos+1 # because of Python index
      pos=posicion(pos+1) #from the next symbol"""

# solution 2. (python ~ for)
"""s1,s2 = open('rosalind_subs.txt').read().split('\r\n')

for i in range(len(s1)):
    if s1[i:].startswith(s2):
        print(i+1)"""

# soution 3. (biopython)
"""from Bio import motifs
from Bio.Seq import Seq
f = 'GATATATGCATATACTT'
p = 'ATAT'
target_seq = Seq(f)
motif = motifs.create([Seq(p)])
for pos,seq in motif.instances.search(target_seq):
    print(str(pos+1),end = ' ')"""