seq = "ATGTAGATGCTTCTTCATATCCGGTGCGGTAAGGCTGAGGCGCGATCGACTTTATGTAACATAGGGTAAGGGGTCATGTACGTTTGACGAAAAAAATAGGGCTCTCCATAAGGGCGACGTATGTAACCGATTGCGGTCCGTTTGACTGTCCGGGAACTGGGGGAGGCCTGGGCTGTCAGCAACAACGTGCTGAAATTTTATTTGGTTGCTGGTTAAAATACTGCCGTACAGCGGAGGGTACTACTATTGTGGAAGAAGCCCCGGAAAGCATGCTGGCCATTCGCCGGATATGATAAAATAATGGTTTGTCGAGTACACAATGGGGTTCGAATACAACCATAGATGAACCACTCGTATTTTACACCAAACCGTCCCTGCTTAGTATACCGGGCGTGGCGGGCACATAACCCTTCCCCCGCACAAGGATGGCTTTATGACGTGCCCTCAAGGCTCAAGACAGGTGAGAAGACAAAGGCAGTCTTCGCTGTTTGCCAAGTTAACTACATCTTATTTGTTGGGCCACACCTTCGCTGTCACCAGGGTCGGAGCTGGACTCTACGTCGGTTCCTGATCATCCATAGGTCGATCAAACGCGCACGCACAACAGCATGCACTATGACAAATACATAGTGGCCATAAGCCCCAGACGGTGGTGATAGCGACGGTCCGCTTGTTAGCCATCTCGCAATCGCATCGGGCATGAGAGACTAATATGGGCCTTAATAAGGGAAATTTATAGGATGCCATGCTCTACTTACGTAGTTAGCTCAGCCAGGCTGGATGCTCATCCAACTCTCACGTACCTTCTATTTCACGGAATGAGGTCATTTGCCACTGTGGAAAGACTAGGATGCGCTTCACGATTCGGTGCTGCGCTTCACTTCCGGACATTCCTGCTTGGAACAGGTAGACGACAGTATCCGGTGACTACAGAATGCGAAACCTATCTTCGCAAGTGACAGAGCCGCATCTACGCGGAGCGTACTGCAAAA"

re_seq = ""
for s in seq:
    if s =="A":
        re_seq += "T"
    elif s =="T":
        re_seq += "A"
    elif s =="G":
        re_seq += "C"
    elif s =="C":
        re_seq += "G"

print(re_seq)

rev_seq = re_seq[::-1]

print(rev_seq)

""" 로잘린드 답안
input S 
reverse S 
for i = 1 to length of S 
     if S[i] = 'A' then S'[i] = 'T'
     if S[i] = 'T' then S'[i] = 'A'
     if S[i] = 'C' then S'[i] = 'G'
     if S[i] = 'G' then S'[i] = 'C'

print S'
"""

#또는
"""
seq = "ATGC"

re_seq = ""

for s in seq:
    if s =="A":
        re_seq += "T"
    elif s =="T":
        re_seq += "A"
    elif s =="G":
        re_seq += "C"
    elif s =="C":
        re_seq += "G"
        
print(''.join(reversed(re_seq)))
"""