seq = "CATGCAACTTGGTGGCGGGCATATTGTAAGCTATTAGGAGGACCAGGGCCCCCGTCGCACTAAACAAGCTAACATGAGAATGTTACAGGTATACCCGTGGAGCATTTAGTTGCATTGTCGCTGGTTCAGAACGTGAAGTGGAAAAAGACTCTTAGCAATTGAGCGGCAATCTCCCGTCTAATTCCCCCAGCTGCAGGTTTCTAATTATAGCGCCGTTATAGCAGTAAATACCAGCATCCGAACCAATGTGCACCGTTCACGGTCTAGGCCTGTGAAACAAACAAGGCGGTTTCAACCGACTTGTGGCGAACTCTAGATCTTGACGGCATCGCCTCAAGGAATAGGACGCGAATCTAAAATTGATGAGCCTGGTTCTACTTGGTCTACGTACACAGGTGCTAGCGCCGCGTGAGCGCAGATGCTACGGTAGTTATTTTCATCACCCTGCTGAGCAGAGAATAGTCCGGAAAATAACTCTAATGCGTTGGTGTCCCTGTGTACAATTTCTTCACGGGATCCGCAGAACAGCAGCAAGATCCGAGCGCAGACACAAACATAAACCTAGAAAACTGTGAGCAGCAGTCGCGGGCGACATCACCGATATGTTTCATAGTTTAGATACGGCATGTATCATCTGTAGGGCTTCTTCTTGAGACCTGCCATACGCTCGCGCTTACGGCATAAAACGCTGCAGCGAGCCGTTAGATTTATTTGTACATGTGTAAGTACCCGGGACAGCGAGTTGCCGGTTGCGCGGTTAGAAACGGCAATCTAATTGAGGCACTTGGACCTCCCATAAAACGTCACAGGCGAATCCGTCGCATAACCGGATATGTAGTGAGCTCAGTAGTCGCTGCCCTACCGTCGATCCGCGTTACGTCGGCAGAGGATATAGATCTCTGTGCAA"
RNA_seq = ""
for s in seq:
    if s =="A":
        RNA_seq += "U"
    if s =="T":
        RNA_seq += "A"
    if s =="G":
        RNA_seq += "C"
    if s =="C":
        RNA_seq += "G"

print(RNA_seq)